In [235]:
import pandas as pd 
import numpy as np

In [236]:
file_path = "c:/Users/vamsh/OneDrive/Desktop/movierecommender/MovieRecommendationSystem/movierecommender/Dataset/tmdb_5000_movies.csv"

df = pd.read_csv(file_path)


df.head(5)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [237]:
df.shape

(4803, 20)

In [238]:
df.isnull().sum()

budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
dtype: int64

In [239]:
df.dropna(inplace=True)

In [240]:
df.isnull().sum()

budget                  0
genres                  0
homepage                0
id                      0
keywords                0
original_language       0
original_title          0
overview                0
popularity              0
production_companies    0
production_countries    0
release_date            0
revenue                 0
runtime                 0
spoken_languages        0
status                  0
tagline                 0
title                   0
vote_average            0
vote_count              0
dtype: int64

In [241]:
df.duplicated().sum()

np.int64(0)

In [242]:
df['release_date'] = pd.to_datetime(df['release_date'])

In [243]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1493 entries, 0 to 4801
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                1493 non-null   int64
 1   genres                1493 non-null   object
 2   homepage              1493 non-null   object
 3   id                    1493 non-null   int64
 4   keywords              1493 non-null   object
 5   original_language     1493 non-null   object
 6   original_title        1493 non-null   object
 7   overview              1493 non-null   object
 8   popularity            1493 non-null   float64
 9   production_companies  1493 non-null   object
 10  production_countries  1493 non-null   object
 11  release_date          1493 non-null   datetime64[ns]
 12  revenue               1493 non-null   int64
 13  runtime               1493 non-null   float64
 14  spoken_languages      1493 non-null   object
 15  status                1493 non-null   object
 16  tagline               1493 non-null   object
 17  title                 1493 non-null   object
 18  vote_average          1493 non-null   float64
 19  vote_count            1493 non-null   int64
dtypes: datetime64[ns](1), float64(3), int64(4), object(12)
memory usage: 244.9+ KB

In [244]:
df.head(3)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466

In [245]:
df.drop(columns={'homepage', 'title', 'production_countries', 'spoken_languages', 'status', 'release_date', 'revenue'}, inplace=True)

In [246]:
df.head(3)

,budget,genres,id,keywords,original_language,original_title,overview,popularity,production_companies,runtime,tagline,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",162.0,Enter the World of Pandora.,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",169.0,"At the end of the world, the adventure begins.",6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",148.0,A Plan No One Escapes,6.3,4466

In [247]:
df.rename(columns={'original_title':'title', 'original_language':'language', 'production_companies': 'production'}, inplace=True)

In [248]:
df.head(3)

,budget,genres,id,keywords,language,title,overview,popularity,production,runtime,tagline,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",162.0,Enter the World of Pandora.,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",169.0,"At the end of the world, the adventure begins.",6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",148.0,A Plan No One Escapes,6.3,4466

In [249]:
df.shape

(1493, 13)

In [250]:
df['vote_average'].describe()

count    1493.000000
mean        6.272873
std         0.970480
min         0.000000
25%         5.800000
50%         6.300000
75%         6.900000
max         8.400000
Name: vote_average, dtype: float64

In [251]:
df.drop(df[df['vote_average']==0].index, inplace=True)

In [252]:
df.head(5)

,budget,genres,id,keywords,language,title,overview,popularity,production,runtime,tagline,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",162.0,Enter the World of Pandora.,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",169.0,"At the end of the world, the adventure begins.",6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",148.0,A Plan No One Escapes,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",165.0,The Legend Ends,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",132.0,"Lost in our world, found in another.",6.1,2124

In [253]:
import ast #to safely evaluate the list

df['genres'] = df['genres'].apply(lambda x: ', '.join([genre['name'] for genre in ast.literal_eval(x)]))

df.head(3)

,budget,genres,id,keywords,language,title,overview,popularity,production,runtime,tagline,vote_average,vote_count
0,237000000,"Action, Adventure, Fantasy, Science Fiction",19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",162.0,Enter the World of Pandora.,7.2,11800
1,300000000,"Adventure, Fantasy, Action",285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",169.0,"At the end of the world, the adventure begins.",6.9,4500
2,245000000,"Action, Adventure, Crime",206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",148.0,A Plan No One Escapes,6.3,4466

In [254]:
df['keywords'][0]

'[{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}]'

In [255]:
df['keywords'] = df['keywords'].apply(lambda x: ', '.join([keyword['name'] for keyword in ast.literal_eval(x)]))

df.head(3)

,budget,genres,id,keywords,language,title,overview,popularity,production,runtime,tagline,vote_average,vote_count
0,237000000,"Action, Adventure, Fantasy, Science Fiction",19995,"culture clash, future, space war, space colony...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",162.0,Enter the World of Pandora.,7.2,11800
1,300000000,"Adventure, Fantasy, Action",285,"ocean, drug abuse, exotic island, east india t...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",169.0,"At the end of the world, the adventure begins.",6.9,4500
2,245000000,"Action, Adventure, Crime",206647,"spy, based on novel, secret agent, sequel, mi6...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",148.0,A Plan No One Escapes,6.3,4466

In [256]:
df['production'] = df['production'].apply(lambda x: ', '.join([keyword['name'] for keyword in ast.literal_eval(x)]))
df.head(3)

,budget,genres,id,keywords,language,title,overview,popularity,production,runtime,tagline,vote_average,vote_count
0,237000000,"Action, Adventure, Fantasy, Science Fiction",19995,"culture clash, future, space war, space colony...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"Ingenious Film Partners, Twentieth Century Fox...",162.0,Enter the World of Pandora.,7.2,11800
1,300000000,"Adventure, Fantasy, Action",285,"ocean, drug abuse, exotic island, east india t...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"Walt Disney Pictures, Jerry Bruckheimer Films,...",169.0,"At the end of the world, the adventure begins.",6.9,4500
2,245000000,"Action, Adventure, Crime",206647,"spy, based on novel, secret agent, sequel, mi6...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"Columbia Pictures, Danjaq, B24",148.0,A Plan No One Escapes,6.3,4466

In [257]:
df['genres'][0]

'Action, Adventure, Fantasy, Science Fiction'

Lower case

In [258]:
df['genres'] = df['genres'].str.lower()

In [259]:
df['keywords'] = df['keywords'].str.lower()
df['title'] = df['title'].str.lower()
df['production'] = df['production'].str.lower()
df['tagline'] = df['tagline'].str.lower()

In [260]:
df.head(3)

,budget,genres,id,keywords,language,title,overview,popularity,production,runtime,tagline,vote_average,vote_count
0,237000000,"action, adventure, fantasy, science fiction",19995,"culture clash, future, space war, space colony...",en,avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"ingenious film partners, twentieth century fox...",162.0,enter the world of pandora.,7.2,11800
1,300000000,"adventure, fantasy, action",285,"ocean, drug abuse, exotic island, east india t...",en,pirates of the caribbean: at world's end,"Captain Barbossa, long believed to be dead, ha...",139.082615,"walt disney pictures, jerry bruckheimer films,...",169.0,"at the end of the world, the adventure begins.",6.9,4500
2,245000000,"action, adventure, crime",206647,"spy, based on novel, secret agent, sequel, mi6...",en,spectre,A cryptic message from Bond’s past sends him o...,107.376788,"columbia pictures, danjaq, b24",148.0,a plan no one escapes,6.3,4466

Remove punctuation

In [261]:
import string

exclude = string.punctuation

In [262]:
exclude

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [263]:
import re
def remove_punc(text):
    if isinstance(text, str):  
        return re.sub(r'[^\w\s]', ' ', text)  # Removes all punctuation
    return text

In [264]:
df = df.map(remove_punc)

In [265]:
df.head(3)

,budget,genres,id,keywords,language,title,overview,popularity,production,runtime,tagline,vote_average,vote_count
0,237000000,action adventure fantasy science fiction,19995,culture clash future space war space colony...,en,avatar,In the 22nd century a paraplegic Marine is di...,150.437577,ingenious film partners twentieth century fox...,162.0,enter the world of pandora,7.2,11800
1,300000000,adventure fantasy action,285,ocean drug abuse exotic island east india t...,en,pirates of the caribbean at world s end,Captain Barbossa long believed to be dead ha...,139.082615,walt disney pictures jerry bruckheimer films ...,169.0,at the end of the world the adventure begins,6.9,4500
2,245000000,action adventure crime,206647,spy based on novel secret agent sequel mi6...,en,spectre,A cryptic message from Bond s past sends him o...,107.376788,columbia pictures danjaq b24,148.0,a plan no one escapes,6.3,4466

In [268]:
df.drop(columns={'language'}, inplace=True)

In [269]:
df.head(5)

,budget,genres,id,keywords,title,overview,popularity,production,runtime,tagline,vote_average,vote_count
0,237000000,action adventure fantasy science fiction,19995,culture clash future space war space colony...,avatar,In the 22nd century a paraplegic Marine is di...,150.437577,ingenious film partners twentieth century fox...,162.0,enter the world of pandora,7.2,11800
1,300000000,adventure fantasy action,285,ocean drug abuse exotic island east india t...,pirates of the caribbean at world s end,Captain Barbossa long believed to be dead ha...,139.082615,walt disney pictures jerry bruckheimer films ...,169.0,at the end of the world the adventure begins,6.9,4500
2,245000000,action adventure crime,206647,spy based on novel secret agent sequel mi6...,spectre,A cryptic message from Bond s past sends him o...,107.376788,columbia pictures danjaq b24,148.0,a plan no one escapes,6.3,4466
3,250000000,action crime drama thriller,49026,dc comics crime fighter terrorist secret id...,the dark knight rises,Following the death of District Attorney Harve...,112.312950,legendary pictures warner bros dc entertain...,165.0,the legend ends,7.6,9106
4,260000000,action adventure science fiction,49529,based on novel mars medallion space travel ...,john carter,John Carter is a war weary former military ca...,43.926995,walt disney pictures,132.0,lost in our world found in another,6.1,2124

In [270]:
df.to_csv("c:/Users/vamsh/OneDrive/Desktop/movierecommender/MovieRecommendationSystem/movierecommender/cleaned data/cleaned_movie_dataset.csv")